#! /bin/sh

#Autoruns
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/hack/launch.sh


#Workspaces
bspc monitor -d I II III IV V VI VII

# Mouse Binding
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Other
bspc config border_width         4
bspc config window_gap          15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a robloxplayerlauncher.exe state=floating
bspc rule -a robloxplayerbeta.exe desktop='^6'
bspc rule -a hl2_linux desktop='^6'
bspc rule -a discord desktop='^3'
bspc rule -a firefox desktop='^2'
bspc rule -a Steam desktop='^5'
